Repository neocodejack/burial-plots, pull requests merged in 2018-06, with the labels that each got.

#52 web.config release ops
  BurialPlots/BurialPlots.csproj
  BurialPlots/RichTextEditor/RichTextEditor.dll
  BurialPlots/WorldPay/Worldpay.Sdk.dll
  burialplots/BurialPlots.csproj
  burialplots/Web.Release.config
  burialplots/Web.config
  burialplots/packages.config
Labels: ops

#53 Adding location in web.config
  burialplots/Web.config
Labels: ops

#54 Updating recaptcha config
  burialplots/Web.Release.config
  burialplots/Web.config
  burialplots/controllers/HomeController.cs
  burialplots/views/Home/LoginSignup.cshtml
Labels: bug, enhancement

#55 Fixing the release config
  burialplots/Web.Release.config
Labels: enhancement

#56 Feature/untagging dynamic images from csproj
  BurialPlots/BurialPlots.csproj
  burialplots/BurialPlots.csproj
  burialplots/areas/admin/views/Login/Index.cshtml
Labels: bug

#57 Feature/agentcode integration
  burialplots/Web.Release.config
  burialplots/Web.config
  burialplots/areas/admin/Controllers/CheckoutsController.cs
  burialplots/areas/admin/js/Checkout/checkout.js
  burialplots/views/Checkout/Index.cshtml
Labels: enhancement

#58 Fixing config changes
  burialplots/Web.Release.config
  burialplots/views/Checkout/Index.cshtml
Labels: enhancement

#60 Changes for functional fix of Agent code
  burialplots/Web.Release.config
  burialplots/Web.config
  burialplots/areas/admin/js/Checkout/checkout.js
  burialplots/controllers/CheckoutController.cs
  burialplots/js/Checkout/index.js
Labels: bug, enhancement

#61 Feature/agentcode integration
  BurialPlots/BurialPlots.csproj
  burialplots/BurialPlots.csproj
Labels: enhancement

#62 Feature/prodconfig
  BurialPlots.sln
  BurialPlots/BurialPlots.csproj
  BurialPlots/Web.Production.config
  burialplots/BurialPlots.csproj
  burialplots/controllers/CheckoutController.cs
Labels: prod config

#64 Feature/paymentrespose
  BurialPlots/BurialPlots.csproj
  BurialPlots/paymentresponse.html
  burialplots/BurialPlots.csproj
  burialplots/views/Shared/_Header.cshtml
Labels: bug
