Repository neocodejack/burial-plots, pull requests merged in 2018-07, with the labels that each got.

#66 Feature/paymentissue
  BurialPlots/BurialPlots.csproj
  BurialPlots/views/Checkout/PaymentResponse.cshtml
  burialplots/BurialPlots.csproj
  burialplots/controllers/CheckoutController.cs
Labels: bug

#67 Changes
  BurialPlots/views/Checkout/PaymentResponse.cshtml
  burialplots/Web.Release.config
  burialplots/Web.config
  burialplots/controllers/CheckoutController.cs
Labels: bug

#68 Changes for api base and return type in caller function
  burialplots/Web.Release.config
  burialplots/views/Checkout/SuccessPayment.cshtml
Labels: bug

#69 Feature/contentfixing tooltip
  BurialPlots/BurialPlots.csproj
  BurialPlots/Scripts/botstrap.bundle.min.js
  BurialPlots/fonts/glyphicons-halflings-regular.eot
  BurialPlots/fonts/glyphicons-halflings-regular.svg
  BurialPlots/fonts/glyphicons-halflings-regular.ttf
  BurialPlots/fonts/glyphicons-halflings-regular.woff
  BurialPlots/fonts/glyphicons-halflings-regular.woff2
  burialplots/App_Start/BundleConfig.cs
  burialplots/BurialPlots.csproj
  burialplots/areas/admin/Controllers/PageController.cs
  burialplots/areas/admin/js/Pagejs.js
  burialplots/areas/admin/views/Page/PageView.cshtml
  burialplots/areas/admin/views/Page/_PopularLocations.cshtml
  burialplots/content/assets/global/plugins/bootstrap/css/bootstrap.css
  burialplots/content/assets/global/plugins/bootstrap/js/bootstrap.js
  burialplots/content/bootstrap.css
  burialplots/content/bootstrap.min.css
  burialplots/style.min.css
  burialplots/views/Shared/_Header.cshtml
Labels: enhancement

#70 Feature/contentfixing tooltip
  BurialPlots/BurialPlots.csproj
  burialplots/BurialPlots.csproj
  burialplots/areas/admin/views/Page/PageView.cshtml
Labels: bug

#71 Display container
  burialplots/areas/admin/views/Page/PageView.cshtml
Labels: enhancement

#72 Changes on popup text and terms and conditions hyper link
  burialplots/areas/admin/views/Page/PageView.cshtml
  burialplots/areas/admin/views/Page/_PopularLocations.cshtml
  burialplots/views/Shared/_Header.cshtml
Labels: bug

#59 Develop
  BurialPlots.sln
  BurialPlots/BurialPlots.csproj
  BurialPlots/Scripts/botstrap.bundle.min.js
  BurialPlots/Web.Production.config
  BurialPlots/fonts/glyphicons-halflings-regular.eot
  BurialPlots/fonts/glyphicons-halflings-regular.svg
  BurialPlots/fonts/glyphicons-halflings-regular.ttf
  BurialPlots/fonts/glyphicons-halflings-regular.woff
  BurialPlots/fonts/glyphicons-halflings-regular.woff2
  BurialPlots/paymentresponse.html
  BurialPlots/views/Checkout/PaymentResponse.cshtml
  burialplots/App_Start/BundleConfig.cs
  burialplots/BurialPlots.csproj
  burialplots/Web.Release.config
  burialplots/Web.config
  burialplots/areas/admin/Controllers/CheckoutsController.cs
  burialplots/areas/admin/Controllers/PageController.cs
  burialplots/areas/admin/js/Checkout/checkout.js
  burialplots/areas/admin/js/Pagejs.js
  burialplots/areas/admin/views/Login/Index.cshtml
  burialplots/areas/admin/views/Page/PageView.cshtml
  burialplots/areas/admin/views/Page/_PopularLocations.cshtml
  burialplots/content/assets/global/plugins/bootstrap/css/bootstrap.css
  burialplots/content/assets/global/plugins/bootstrap/js/bootstrap.js
  burialplots/content/bootstrap.css
  burialplots/content/bootstrap.min.css
  burialplots/controllers/CheckoutController.cs
  burialplots/controllers/HomeController.cs
  burialplots/js/Checkout/index.js
  burialplots/style.min.css
  burialplots/views/Checkout/Index.cshtml
  burialplots/views/Checkout/SuccessPayment.cshtml
  burialplots/views/Home/LoginSignup.cshtml
  burialplots/views/Shared/_Header.cshtml
Labels: prod sync pr

#73 Cemetary Menu fix
  burialplots/views/Shared/_Header.cshtml
Labels: bug

#74 Develop
  burialplots/views/Shared/_Header.cshtml
Labels: bug
